language: cpp
before_install:
  - sed -i -e 's|AC_PREREQ(\[2.69\])|AC_PREREQ([2.68])|' configure.ac
  - sudo apt-get update -qq
install:
  - mkdir sdl_root
  - export SDL_PREFIX="$PWD/sdl_root"
  - export PATH="$SDL_PREFIX/bin:$PATH"
  - export PKG_CONFIG_PATH="$SDL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  - wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz -O - | tar -xz
  - (cd SDL2-2.0.3 && ./configure --prefix=$SDL_PREFIX && make -j5 && make install)
  - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz -O - | tar -xz
  - (cd SDL2_mixer-2.0.0 && ./configure --prefix=$SDL_PREFIX && make -j5 && make install)
script: ./bootstrap && ./configure --enable-sdl2-mixer && make -j5
compiler:
  - gcc
  - clang
