version: '{build}'

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

cache:
  - C:\sdl_root

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))

  # SDL2
  - ps: |
      $SDL_VERSION = "2.0.4"
      $SDL_PREFIX = "C:\sdl_root\SDL2-$SDL_VERSION"
      if (!(Test-Path -Path $SDL_PREFIX)) {
        Start-FileDownload https://libsdl.org/release/SDL2-devel-$SDL_VERSION-VC.zip
        7z x SDL2-devel-$SDL_VERSION-VC.zip -oC:\sdl_root\
      }
      $env:SDL2_INCLUDE = "$SDL_PREFIX\include"
      $env:SDL2_LIB = "$SDL_PREFIX\lib"

  # SDL2_mixer
  - ps: |
      $SDL_MIXER_VERSION = "2.0.1"
      $SDL_MIXER_PREFIX = "C:\sdl_root\SDL2_mixer-$SDL_MIXER_VERSION"
      if (!(Test-Path -Path $SDL_MIXER_PREFIX)) {
        Start-FileDownload https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-$SDL_MIXER_VERSION-VC.zip
        7z x SDL2_mixer-devel-$SDL_MIXER_VERSION-VC.zip -oC:\sdl_root\
      }
      $env:SDL2_MIXER_INCLUDE = "$SDL_MIXER_PREFIX\include"
      $env:SDL2_MIXER_LIB = "$SDL_MIXER_PREFIX\lib"

build_script:
  - msbuild windows\freeserf.sln

after_build:
  - ps: |
      $ZIP_BASE = "freeserf-VC-$env:PLATFORM-$env:CONFIGURATION-$env:APPVEYOR_BUILD_NUMBER"
      $ZIP_FILE = "$($ZIP_BASE).zip"
      md $ZIP_BASE
      Copy-Item -Path windows\$env:PLATFORM\$env:CONFIGURATION\freeserf.exe -Destination $ZIP_BASE\
      Copy-Item -Path README.md -Destination $ZIP_BASE\README.txt
      Copy-Item -Path windows\$env:PLATFORM\$env:CONFIGURATION\SDL2.dll -Destination $ZIP_BASE\
      Copy-Item -Path windows\$env:PLATFORM\$env:CONFIGURATION\SDL2_mixer.dll -Destination $ZIP_BASE\
      7z a $ZIP_FILE $ZIP_BASE\*
      Push-AppveyorArtifact $ZIP_FILE
