os: Visual Studio 2015

version: '{build}'

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

cache:
  - C:\sdl_root

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))

  # SDL2
  - ps: |
      $SDL_VERSION = "2.0.4"
      $SDL_PREFIX = "C:\sdl_root\SDL2-$SDL_VERSION"
      if (!(Test-Path -Path $SDL_PREFIX)) {
        Start-FileDownload https://libsdl.org/release/SDL2-devel-$SDL_VERSION-VC.zip
        7z x SDL2-devel-$SDL_VERSION-VC.zip -oC:\sdl_root\
      }
      $env:SDL2_INCLUDE = "$SDL_PREFIX\include"
      $env:SDL2_LIB = "$SDL_PREFIX\lib"

  # SDL2_mixer
  - ps: |
      $SDL_MIXER_VERSION = "2.0.1"
      $SDL_MIXER_PREFIX = "C:\sdl_root\SDL2_mixer-$SDL_MIXER_VERSION"
      if (!(Test-Path -Path $SDL_MIXER_PREFIX)) {
        Start-FileDownload https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-$SDL_MIXER_VERSION-VC.zip
        7z x SDL2_mixer-devel-$SDL_MIXER_VERSION-VC.zip -oC:\sdl_root\
      }
      $env:SDL2_MIXER_INCLUDE = "$SDL_MIXER_PREFIX\include"
      $env:SDL2_MIXER_LIB = "$SDL_MIXER_PREFIX\lib"

  # libxmp
  - if "%platform%" == "x86" call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%platform%" == "x64" call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - ps: |
      $XMP_VERSION = "4.4.1"
      $XMP_PREFIX = "C:\sdl_root\XMP-$XMP_VERSION"
      if (!(Test-Path "$XMP_PREFIX\lib\$env:PLATFORM\libxmp.lib")) {
        Start-FileDownload https://sourceforge.net/projects/xmp/files/libxmp/$XMP_VERSION/libxmp-$XMP_VERSION.tar.gz
        7z x "libxmp-$XMP_VERSION.tar.gz"
        7z x "libxmp-$XMP_VERSION.tar"
        cd libxmp-$XMP_VERSION
        nmake Makefile.vc
        md $XMP_PREFIX
        md $XMP_PREFIX\include
        md $XMP_PREFIX\lib
        md $XMP_PREFIX\lib\$env:PLATFORM
        Copy-Item -Path libxmp.dll -Destination $XMP_PREFIX\lib\$env:PLATFORM
        Copy-Item -Path libxmp.lib -Destination $XMP_PREFIX\lib\$env:PLATFORM
        Copy-Item -Path libxmp.exp -Destination $XMP_PREFIX\lib\$env:PLATFORM
        Copy-Item -Path include\xmp.h -Destination $XMP_PREFIX\include
        cd ..
      }
      $env:XMP_INCLUDE = "$XMP_PREFIX\include"
      $env:XMP_LIB = "$XMP_PREFIX\lib"

build_script:
  - msbuild windows\freeserf.sln

after_build:
  - ps: |
      $ZIP_BASE = "freeserf-VC-$env:PLATFORM-$env:CONFIGURATION"
      $ZIP_FILE = "$($ZIP_BASE).zip"
      md $ZIP_BASE
      Copy-Item -Path windows\$env:PLATFORM\$env:CONFIGURATION\freeserf.exe -Destination $ZIP_BASE\
      Copy-Item -Path README.md -Destination $ZIP_BASE\README.txt
      Copy-Item -Path windows\$env:PLATFORM\$env:CONFIGURATION\SDL2.dll -Destination $ZIP_BASE\
      Copy-Item -Path windows\$env:PLATFORM\$env:CONFIGURATION\SDL2_mixer.dll -Destination $ZIP_BASE\
      Copy-Item -Path windows\$env:PLATFORM\$env:CONFIGURATION\libxmp.dll -Destination $ZIP_BASE\
      7z a $ZIP_FILE $ZIP_BASE\*
      Push-AppveyorArtifact $ZIP_FILE
